apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: services
spec:
  selector:
    app: my-todoui
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 80
  type: LoadBalancer